In [1]:
#Import pandas, matplotlib.pyplot, and seaborn 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json

from library.sb_utils import save_file

In [2]:
#Function to display the full dataframe
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

# Importing nested json into pandas dataframe

In [3]:
with open('./data/hymnal_data_export.json', encoding="utf8") as f:
    data = f.readlines()
    data = [json.loads(line) for line in data]

In [4]:
df = pd.json_normalize(data, max_level=1)

### Checking out nested dataframe

In [5]:
df.head(2).T

,0,1
event_date,20201107,20201107
event_timestamp,1604801718108000,1604785674744000
event_name,session_start,session_start
event_params,"[{'key': 'firebase_event_origin', 'value': {'s...","[{'key': 'ga_session_number', 'value': {'int_v..."
event_previous_timestamp,1604785674744000,1604680637311000
event_bundle_sequence_id,13,12
event_server_timestamp_offset,754702,718754
user_pseudo_id,cb052c8ce7b261aecf783ce043089fb3,cb052c8ce7b261aecf783ce043089fb3
user_properties,"[{'key': 'ga_session_id', 'value': {'int_value...","[{'key': 'ga_session_number', 'value': {'int_v..."
user_first_touch_timestamp,1562977643627000,1562977643627000
stream_id,1440534155,1440534155
platform,ANDROID,ANDROID
items,[],[]
device.category,mobile,mobile
device.mobile_brand_name,Google,Google
device.mobile_model_name,Pixel,Pixel
device.mobile_os_hardware_model,Pixel,Pixel
device.operating_system,ANDROID,ANDROID
device.operating_system_version,10,10
device.language,en-us,en-us
device.is_limited_ad_tracking,No,No
device.time_zone_offset_seconds,-21600,-21600
geo.continent,Americas,Americas
geo.country,United States,United States
geo.region,Texas,Texas
geo.city,Austin,Austin
geo.sub_continent,Northern America,Northern America
geo.metro,(not set),(not set)
app_info.id,org.livingletter.hymnal,org.livingletter.hymnal
app_info.version,1.1.7,1.1.7
app_info.firebase_app_id,1:76837103840:android:e1d753a7fbfeeaac,1:76837103840:android:e1d753a7fbfeeaac
app_info.install_source,com.android.vending,com.android.vending
traffic_source.medium,organic,organic
traffic_source.source,google-play,google-play
ecommerce.unique_items,NaN,NaN
device.mobile_marketing_name,NaN,NaN
traffic_source.name,NaN,NaN
device.vendor_id,NaN,NaN
ecommerce.transaction_id,NaN,NaN

Here we see that only 'event_params' and 'user_properties' are still nested.

### Creating index column as reference for merging dataframes

In [6]:
#Creating index column for merging reference later on
df['index1'] = df.index
df.head(1).T

                                                                                 0
event_date                                                                20201107
event_timestamp                                                   1604801718108000
event_name                                                           session_start
event_params                     [{'key': 'firebase_event_origin', 'value': {'s...
event_previous_timestamp                                          1604785674744000
event_bundle_sequence_id                                                        13
event_server_timestamp_offset                                               754702
user_pseudo_id                                    cb052c8ce7b261aecf783ce043089fb3
user_properties                  [{'key': 'ga_session_id', 'value': {'int_value...
user_first_touch_timestamp                                        1562977643627000
stream_id                                                               1440534155
platform                                                                   ANDROID
items                                                                           []
device.category                                                             mobile
device.mobile_brand_name                                                    Google
device.mobile_model_name                                                     Pixel
device.mobile_os_hardware_model                                              Pixel
device.operating_system                                                    ANDROID
device.operating_system_version                                                 10
device.language                                                              en-us
device.is_limited_ad_tracking                                                   No
device.time_zone_offset_seconds                                             -21600
geo.continent                                                             Americas
geo.country                                                          United States
geo.region                                                                   Texas
geo.city                                                                    Austin
geo.sub_continent                                                 Northern America
geo.metro                                                                (not set)
app_info.id                                                org.livingletter.hymnal
app_info.version                                                             1.1.7
app_info.firebase_app_id                    1:76837103840:android:e1d753a7fbfeeaac
app_info.install_source                                        com.android.vending
traffic_source.medium                                                      organic
traffic_source.source                                                  google-play
ecommerce.unique_items                                                         NaN
device.mobile_marketing_name                                                   NaN
traffic_source.name                                                            NaN
device.vendor_id                                                               NaN
ecommerce.transaction_id                                                       NaN
index1                                                                           0

### Saving normalized json as main json file for dataframe

In [7]:
# Saving normalized df as formatted json
with open('./data/hymnal_data_formatted.json', 'w') as f:
    data1 = f.write(df.to_json(orient='records', lines=True))

In [8]:
# Opening json file by reading each line as a new object
with open('./data/hymnal_data_formatted.json', encoding="utf8") as f:
    data1 = f.readlines()
    data1 = [json.loads(line) for line in data1]

# Dealing with nested event_params

In [9]:
df_event_params = pd.json_normalize(
    data1, 
    record_path='event_params',
    record_prefix='params_',
    meta=['index1'],
    max_level=1
    )
print(df_event_params.params_key.unique())
df_event_params

['firebase_event_origin' 'ga_session_id' 'engaged_session_event'
 'session_engaged' 'ga_session_number' 'firebase_screen_id'
 'firebase_screen_class' 'engagement_time_msec' 'entrances' 'freeride'
 'firebase_previous_id' 'firebase_previous_class' 'item_subcategory'
 'recommended' 'item_category' 'item_name' 'item_number' 'item_id'
 'debug_event' 'timestamp' 'previous_os_version' 'campaign_info_source'
 'medium' 'source' 'system_app' 'system_app_update'
 'update_with_analytics' 'firebase_conversion' 'previous_first_open_count'
 'search_term' 'search_book' 'search_type' 'search_subcategory'
 'search_category' 'previous_app_version']

,params_key,params_value.string_value,params_value.int_value,params_value.double_value,index1
0,firebase_event_origin,auto,NaN,NaN,0
1,ga_session_id,NaN,1604801718,NaN,0
2,engaged_session_event,NaN,1,NaN,0
3,session_engaged,NaN,1,NaN,0
4,ga_session_number,NaN,8,NaN,0
...,...,...,...,...,...
86127,recommended,NaN,0,NaN,10938
86128,firebase_screen_class,MainActivity,NaN,NaN,10938
86129,item_subcategory,Life in Eternity,NaN,NaN,10938
86130,ga_session_number,NaN,121,NaN,10938
86131,item_number,NaN,984,NaN,10938

In [10]:
df_event_params.params_key.value_counts()

firebase_event_origin        10939
ga_session_id                10921
ga_session_number            10921
engaged_session_event        10645
firebase_screen_id           10486
firebase_screen_class        10486
engagement_time_msec          4707
firebase_previous_id          3629
firebase_previous_class       3629
recommended                    974
item_name                      974
item_number                    974
item_id                        974
item_category                  951
item_subcategory               904
search_type                    802
search_term                    802
search_book                    802
entrances                      473
session_engaged                452
debug_event                    242
freeride                       212
search_category                 59
search_subcategory              59
previous_os_version             57
timestamp                       11
previous_first_open_count       10
update_with_analytics           10
firebase_conversion             10
source                           3
system_app_update                3
system_app                       3
campaign_info_source             3
medium                           3
previous_app_version             2
Name: params_key, dtype: int64

In [11]:
df_event_params = df_event_params.set_index(['index1', 'params_key'])

### Creating for loops to clean event_params dataframe

In [12]:
parameters = ['firebase_event_origin', 'ga_session_id', 'engaged_session_event',
       'session_engaged', 'ga_session_number', 'firebase_screen_id',
       'firebase_screen_class', 'engagement_time_msec', 'entrances',
       'freeride', 'firebase_previous_id', 'firebase_previous_class',
       'item_subcategory', 'recommended', 'item_category', 'item_name',
       'item_number', 'item_id', 'debug_event', 
       'previous_os_version', 'campaign_info_source', 'medium', 'source',
       'system_app', 'system_app_update', 'update_with_analytics',
       'firebase_conversion', 'previous_first_open_count', 'search_term',
       'search_book', 'search_type', 'search_subcategory', 'search_category',
       'previous_app_version']
df_dict = {}

for i in parameters:
    df_name = 'df_' + i 
    df_dict[df_name] = df_event_params.xs(i, level=1, drop_level=False).reset_index(level=[0,1], drop=False)
    df_dict[df_name] = df_dict[df_name].dropna(axis=1)
    df_dict[df_name] = df_dict[df_name].rename(columns={df_dict[df_name].columns[2]:df_dict[df_name].iloc[0,1]})
    df_dict[df_name] = df_dict[df_name].drop(columns=df_dict[df_name].columns[1])

In [13]:
# Checking the shape of newly created dataframe
for i in parameters:
    print('Shape of df_' + i + ':', df_dict['df_'+i].shape)

Shape of df_firebase_event_origin: (10939, 2)
Shape of df_ga_session_id: (10921, 2)
Shape of df_engaged_session_event: (10645, 2)
Shape of df_session_engaged: (452, 2)
Shape of df_ga_session_number: (10921, 2)
Shape of df_firebase_screen_id: (10486, 2)
Shape of df_firebase_screen_class: (10486, 2)
Shape of df_engagement_time_msec: (4707, 2)
Shape of df_entrances: (473, 2)
Shape of df_freeride: (212, 2)
Shape of df_firebase_previous_id: (3629, 2)
Shape of df_firebase_previous_class: (3629, 2)
Shape of df_item_subcategory: (904, 2)
Shape of df_recommended: (974, 2)
Shape of df_item_category: (951, 2)
Shape of df_item_name: (974, 2)
Shape of df_item_number: (974, 2)
Shape of df_item_id: (974, 2)
Shape of df_debug_event: (242, 2)
Shape of df_previous_os_version: (57, 2)
Shape of df_campaign_info_source: (3, 2)
Shape of df_medium: (3, 2)
Shape of df_source: (3, 2)
Shape of df_system_app: (3, 2)
Shape of df_system_app_update: (3, 2)
Shape of df_update_with_analytics: (10, 2)
Shape of df_firebase_conversion: (10, 2)
Shape of df_previous_first_open_count: (10, 2)
Shape of df_search_term: (802, 2)
Shape of df_search_book: (802, 2)
Shape of df_search_type: (802, 2)
Shape of df_search_subcategory: (59, 2)
Shape of df_search_category: (59, 2)
Shape of df_previous_app_version: (2, 2)

In [14]:
 # Timestamp was singled out since it had NaN values in columns where values existed
df_timestamp = df_event_params.xs('timestamp', level=1, drop_level=False)\
    .reset_index(level=[0,1], drop=False)\
    .drop(labels=['params_value.string_value','params_key'], axis=1)\
    .rename(columns={'params_value.int_value':'timestamp','params_value.double_value':'timestamp_double'})
df_timestamp

    index1   timestamp  timestamp_double
0      315  1604771210               NaN
1      482         NaN      1.604788e+09
2     2542  1604757574               NaN
3     2576  1604760358               NaN
4     3465         NaN      1.604750e+09
5     4448         NaN      1.604737e+09
6     4449         NaN      1.604745e+09
7     6047         NaN      1.604802e+09
8     6048         NaN      1.604803e+09
9     8031         NaN      1.604801e+09
10    8032         NaN      1.604800e+09

In [15]:
# Merging all sub-dataframes into one
df_event_params = df_dict['df_'+parameters[0]]
for i in parameters:
    df_event_params = df_event_params.merge(df_dict['df_'+i], on='index1', how='left')

df_event_params = df_event_params.merge(df_timestamp, on='index1', how='left')

In [16]:
df_event_params.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10939 entries, 0 to 10938
Data columns (total 38 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index1                     10939 non-null  int64
 1   firebase_event_origin_x    10939 non-null  object
 2   firebase_event_origin_y    10939 non-null  object
 3   ga_session_id              10921 non-null  object
 4   engaged_session_event      10645 non-null  object
 5   session_engaged            452 non-null    object
 6   ga_session_number          10921 non-null  object
 7   firebase_screen_id         10486 non-null  object
 8   firebase_screen_class      10486 non-null  object
 9   engagement_time_msec       4707 non-null   object
 10  entrances                  473 non-null    object
 11  freeride                   212 non-null    object
 12  firebase_previous_id       3629 non-null   object
 13  firebase_previous_class    3629 non-null   object
 14  item_subcategory           904 non-null    object
 15  recommended                974 non-null    object
 16  item_category              951 non-null    object
 17  item_name                  974 non-null    object
 18  item_number                974 non-null    object
 19  item_id                    974 non-null    object
 20  debug_event                242 non-null    object
 21  previous_os_version        57 non-null     object
 22  campaign_info_source       3 non-null      object
 23  medium                     3 non-null      object
 24  source                     3 non-null      object
 25  system_app                 3 non-null      object
 26  system_app_update          3 non-null      object
 27  update_with_analytics      10 non-null     object
 28  firebase_conversion        10 non-null     object
 29  previous_first_open_count  10 non-null     object
 30  search_term                802 non-null    object
 31  search_book                802 non-null    object
 32  search_type                802 non-null    object
 33  search_subcategory         59 non-null     object
 34  search_category            59 non-null     object
 35  previous_app_version       2 non-null      object
 36  timestamp                  3 non-null      object
 37  timestamp_double           8 non-null      float64
dtypes: float64(1), int64(1), object(36)
memory usage: 3.3+ MB

# Dealing with nested user_properties

In [17]:
df_user_properties = pd.json_normalize(
    data1, 
    record_path='user_properties',
    record_prefix='user_',
    meta=['index1'],
    max_level=1
    )
print(df_user_properties.user_key.unique())
df_user_properties

['ga_session_id' 'first_open_time' 'ga_session_number']

,user_key,user_value.int_value,user_value.set_timestamp_micros,index1
0,ga_session_id,1604801718,1604801718108000,0
1,first_open_time,1562979600000,1562977643627000,0
2,ga_session_number,8,1604801718108000,0
3,ga_session_number,7,1604785674744000,1
4,ga_session_id,1604785674,1604785674744000,1
...,...,...,...,...
32776,ga_session_id,1604783430,1604783430866000,10937
32777,first_open_time,1578348000000,1578347879890000,10937
32778,ga_session_number,121,1604764472262000,10938
32779,first_open_time,1584248400000,1584248039606000,10938
32780,ga_session_id,1604764472,1604764472262000,10938

### Saving normalized json as main json file for dataframe

In [18]:
# Here I see some missing rows for ga_session_number and ga_session_id
df_user_properties.user_key.value_counts()

first_open_time      10939
ga_session_id        10921
ga_session_number    10921
Name: user_key, dtype: int64

In [19]:
#Grouping user_properties dataframe by user_key
df_user_properties_grouped = df_user_properties.groupby(by='user_key')
df_user_properties_grouped.first()

                  user_value.int_value user_value.set_timestamp_micros  index1
user_key
first_open_time          1562979600000                1562977643627000       0
ga_session_id               1604801718                1604801718108000       0
ga_session_number                    8                1604801718108000       0

In [20]:
#Splitting up each groupby groups into a separate dataframe with new column names
df_user_properties_grouped1 = df_user_properties_grouped.get_group('ga_session_id').reset_index().rename(columns = {'user_value.int_value':'ga_session_id.value', 'user_value.set_timestamp_micros':'ga_session_id.timestamp'})
df_user_properties_grouped2 = df_user_properties_grouped.get_group('ga_session_number').reset_index().rename(columns = {'user_value.int_value':'ga_session_number.value', 'user_value.set_timestamp_micros':'ga_session_number.timestamp'})
df_user_properties_grouped3 = df_user_properties_grouped.get_group('first_open_time').reset_index().rename(columns = {'user_value.int_value':'first_open_time.value', 'user_value.set_timestamp_micros':'first_open_time.timestamp'})

In [21]:
#Deleting index column
df_user_properties_grouped1.drop('index', 1, inplace=True)
df_user_properties_grouped2.drop('index', 1, inplace=True)
df_user_properties_grouped3.drop('index', 1, inplace=True)

In [22]:
print('Shape of grouped1', df_user_properties_grouped1.shape)
print('Shape of grouped2', df_user_properties_grouped2.shape)
print('Shape of grouped3', df_user_properties_grouped3.shape)
#Here I see that there are missing data in grouped1 and grouped2

Shape of grouped1 (10921, 3)
Shape of grouped2 (10921, 3)
Shape of grouped3 (10939, 3)

In [23]:
# testing merge function for shape
pd.merge(df_user_properties_grouped3,df_user_properties_grouped2, how='left', on=['index1'])

,first_open_time.value,first_open_time.timestamp,index1,ga_session_number.value,ga_session_number.timestamp
0,1562979600000,1562977643627000,0,8,1604801718108000
1,1562979600000,1562977643627000,1,7,1604785674744000
2,1562979600000,1562977643627000,2,7,1604785674744000
3,1562979600000,1562977643627000,3,7,1604785674744000
4,1562979600000,1562977643627000,4,7,1604785674744000
...,...,...,...,...,...
10934,1578348000000,1578347879890000,10934,359,1604783430866000
10935,1578348000000,1578347879890000,10935,359,1604783430866000
10936,1578348000000,1578347879890000,10936,359,1604783430866000
10937,1578348000000,1578347879890000,10937,359,1604783430866000
10938,1584248400000,1584248039606000,10938,121,1604764472262000

In [24]:
#Merging 3 dataframes on index1 based on grouped3 since it has the correct number of rows as original dataframe
df_user_properties_grouped_all = df_user_properties_grouped3.merge(df_user_properties_grouped2, how='left').merge(df_user_properties_grouped1, how='left')

In [25]:
df_user_properties_grouped_all.head(1).T

                                            0
first_open_time.value           1562979600000
first_open_time.timestamp    1562977643627000
index1                                      0
ga_session_number.value                     8
ga_session_number.timestamp  1604801718108000
ga_session_id.value                1604801718
ga_session_id.timestamp      1604801718108000

### Converting to appropriate dtypes

In [26]:
#Converting dtypes to int in order to match dtype in df_0 dataframe
df_user_properties_grouped_all['first_open_time.value'] = pd.to_numeric(df_user_properties_grouped_all['first_open_time.value'])
df_user_properties_grouped_all['ga_session_id.value'] = pd.to_numeric(df_user_properties_grouped_all['ga_session_id.value'])
df_user_properties_grouped_all['ga_session_number.value'] = pd.to_numeric(df_user_properties_grouped_all['ga_session_number.value'])

df_user_properties_grouped_all.dtypes

first_open_time.value            int64
first_open_time.timestamp       object
index1                          object
ga_session_number.value        float64
ga_session_number.timestamp     object
ga_session_id.value            float64
ga_session_id.timestamp         object
dtype: object

### Merging cleaned user_properties and event_params dataframe into main dataframe

In [27]:
# Merging user_properties into original dataframe
df_merge1 = df.merge(df_user_properties_grouped_all, how='left', on='index1')
print(df_merge1.shape)
df_merge1.head(1)

(10939, 46)

,event_date,event_timestamp,event_name,event_params,event_previous_timestamp,event_bundle_sequence_id,event_server_timestamp_offset,user_pseudo_id,user_properties,user_first_touch_timestamp,...,traffic_source.name,device.vendor_id,ecommerce.transaction_id,index1,first_open_time.value,first_open_time.timestamp,ga_session_number.value,ga_session_number.timestamp,ga_session_id.value,ga_session_id.timestamp
0,20201107,1604801718108000,session_start,"[{'key': 'firebase_event_origin', 'value': {'s...",1604785674744000,13,754702,cb052c8ce7b261aecf783ce043089fb3,"[{'key': 'ga_session_id', 'value': {'int_value...",1562977643627000,...,NaN,NaN,NaN,0,1562979600000,1562977643627000,8.0,1604801718108000,1.604802e+09,1604801718108000

In [28]:
# Merging event_params into original dataframe
df_merge1 = df_merge1.merge(df_event_params, how='left', on='index1')
print(df_merge1.shape)
df_merge1.head(1)

(10939, 83)

,event_date,event_timestamp,event_name,event_params,event_previous_timestamp,event_bundle_sequence_id,event_server_timestamp_offset,user_pseudo_id,user_properties,user_first_touch_timestamp,...,firebase_conversion,previous_first_open_count,search_term,search_book,search_type,search_subcategory,search_category,previous_app_version,timestamp,timestamp_double
0,20201107,1604801718108000,session_start,"[{'key': 'firebase_event_origin', 'value': {'s...",1604785674744000,13,754702,cb052c8ce7b261aecf783ce043089fb3,"[{'key': 'ga_session_id', 'value': {'int_value...",1562977643627000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# Deleting original nested column
df_merge1 = df_merge1.drop(['user_properties','event_params','items'], axis=1)

In [30]:
# Displaying full columns of first row of dataframe
print_full(df_merge1.head(1).T)

                                                                      0
event_date                                                     20201107
event_timestamp                                        1604801718108000
event_name                                                session_start
event_previous_timestamp                               1604785674744000
event_bundle_sequence_id                                             13
event_server_timestamp_offset                                    754702
user_pseudo_id                         cb052c8ce7b261aecf783ce043089fb3
user_first_touch_timestamp                             1562977643627000
stream_id                                                    1440534155
platform                                                        ANDROID
device.category                                                  mobile
device.mobile_brand_name                                         Google
device.mobile_model_name                                          Pixel
device.mobile_os_hardware_model                                   Pixel
device.operating_system                                         ANDROID
device.operating_system_version                                      10
device.language                                                   en-us
device.is_limited_ad_tracking                                        No
device.time_zone_offset_seconds                                  -21600
geo.continent                                                  Americas
geo.country                                               United States
geo.region                                                        Texas
geo.city                                                         Austin
geo.sub_continent                                      Northern America
geo.metro                                                     (not set)
app_info.id                                     org.livingletter.hymnal
app_info.version                                                  1.1.7
app_info.firebase_app_id         1:76837103840:android:e1d753a7fbfeeaac
app_info.install_source                             com.android.vending
traffic_source.medium                                           organic
traffic_source.source                                       google-play
ecommerce.unique_items                                              NaN
device.mobile_marketing_name                                        NaN
traffic_source.name                                                 NaN
device.vendor_id                                                    NaN
ecommerce.transaction_id                                            NaN
index1                                                                0
first_open_time.value                                     1562979600000
first_open_time.timestamp                              1562977643627000
ga_session_number.value                                               8
ga_session_number.timestamp                            1604801718108000
ga_session_id.value                                          1.6048e+09
ga_session_id.timestamp                                1604801718108000
firebase_event_origin_x                                            auto
firebase_event_origin_y                                            auto
ga_session_id                                                1604801718
engaged_session_event                                                 1
session_engaged                                                       1
ga_session_number                                                     8
firebase_screen_id                                                  NaN
firebase_screen_class                                               NaN
engagement_time_msec                                                NaN
entrances                                                           NaN
freeride                                                            NaN
firebase_previous_id                                                NaN
firebase_previous_class                                             NaN
item_subcategory                                                    NaN
recommended                                                         NaN
item_category                                                       NaN
item_name                                                           NaN
item_number                                                         NaN
item_id                                                             NaN
debug_event                                                         NaN
previous_os_version                                                 NaN
campaign_info_source                                                NaN
medium                                                              NaN
source                                                              NaN
system_app                                                          NaN
system_app_update                                                   NaN
update_with_analytics                                               NaN
firebase_conversion                                                 NaN
previous_first_open_count                                           NaN
search_term                                                         NaN
search_book                                                         NaN
search_type                                                         NaN
search_subcategory                                                  NaN
search_category                                                     NaN
previous_app_version                                                NaN
timestamp                                                           NaN
timestamp_double                                                    NaN

I would like to check out NAN values in each column before deciding whether to retain or remove from the dataframe.

### Checking out NAN rows

In [31]:
# Displaying columns with null values only
df_merge1[df_merge1.columns[df_merge1.isnull().any()]].isnull().sum()

event_previous_timestamp           81
device.mobile_brand_name          242
device.mobile_model_name          242
ecommerce.unique_items           9965
device.mobile_marketing_name    10262
traffic_source.name               678
device.vendor_id                 1013
ecommerce.transaction_id        10932
ga_session_number.value            18
ga_session_number.timestamp        18
ga_session_id.value                18
ga_session_id.timestamp            18
ga_session_id                      18
engaged_session_event             294
session_engaged                 10487
ga_session_number                  18
firebase_screen_id                453
firebase_screen_class             453
engagement_time_msec             6232
entrances                       10466
freeride                        10727
firebase_previous_id             7310
firebase_previous_class          7310
item_subcategory                10035
recommended                      9965
item_category                    9988
item_name                        9965
item_number                      9965
item_id                          9965
debug_event                     10697
previous_os_version             10882
campaign_info_source            10936
medium                          10936
source                          10936
system_app                      10936
system_app_update               10936
update_with_analytics           10929
firebase_conversion             10929
previous_first_open_count       10929
search_term                     10137
search_book                     10137
search_type                     10137
search_subcategory              10880
search_category                 10880
previous_app_version            10937
timestamp                       10936
timestamp_double                10931
dtype: int64

# Converting event_timestamp column to readable datetime format

In [32]:
#Checking for duplicated event_timestamp to see if I could use this column to sort my data
df_merge1.event_timestamp.duplicated().sum()

17

### Formatting firebase (event_, ga_session_) timestamp
"Firebase.ServerValue.TIMESTAMP is not actual timestamp it is constant that will be replaced with actual value in server if you have it set into some variable."

In [33]:
list1 = ['event_date', 'event_timestamp', 'event_previous_timestamp', 'user_first_touch_timestamp', 'first_open_time.timestamp', 'ga_session_number.timestamp', 'ga_session_id.timestamp']
for i in list1:
    df_merge1[i] = pd.to_datetime(df_merge1[i], unit='us')

In [34]:
df_merge1.select_dtypes(include='datetime64')

,event_date,event_timestamp,event_previous_timestamp,user_first_touch_timestamp,first_open_time.timestamp,ga_session_number.timestamp,ga_session_id.timestamp
0,1970-01-01 00:00:20.201107,2020-11-08 02:15:18.108000,2020-11-07 21:47:54.744000,2019-07-13 00:27:23.627,2019-07-13 00:27:23.627,2020-11-08 02:15:18.108,2020-11-08 02:15:18.108
1,1970-01-01 00:00:20.201107,2020-11-07 21:47:54.744000,2020-11-06 16:37:17.311000,2019-07-13 00:27:23.627,2019-07-13 00:27:23.627,2020-11-07 21:47:54.744,2020-11-07 21:47:54.744
2,1970-01-01 00:00:20.201107,2020-11-07 21:47:56.284001,2020-11-06 16:38:57.941001,2019-07-13 00:27:23.627,2019-07-13 00:27:23.627,2020-11-07 21:47:54.744,2020-11-07 21:47:54.744
3,1970-01-01 00:00:20.201107,2020-11-07 21:48:45.805005,2020-11-07 21:48:24.899005,2019-07-13 00:27:23.627,2019-07-13 00:27:23.627,2020-11-07 21:47:54.744,2020-11-07 21:47:54.744
4,1970-01-01 00:00:20.201107,2020-11-07 21:48:45.964006,2020-11-07 21:48:24.920006,2019-07-13 00:27:23.627,2019-07-13 00:27:23.627,2020-11-07 21:47:54.744,2020-11-07 21:47:54.744
...,...,...,...,...,...,...,...
10934,1970-01-01 00:00:20.201107,2020-11-07 21:10:30.866000,2020-11-06 11:03:48.569000,2020-01-06 21:57:59.890,2020-01-06 21:57:59.890,2020-11-07 21:10:30.866,2020-11-07 21:10:30.866
10935,1970-01-01 00:00:20.201107,2020-11-07 21:17:57.078004,2020-11-07 21:16:01.687004,2020-01-06 21:57:59.890,2020-01-06 21:57:59.890,2020-11-07 21:10:30.866,2020-11-07 21:10:30.866
10936,1970-01-01 00:00:20.201107,2020-11-07 21:10:31.489001,2020-11-06 11:03:53.104001,2020-01-06 21:57:59.890,2020-01-06 21:57:59.890,2020-11-07 21:10:30.866,2020-11-07 21:10:30.866
10937,1970-01-01 00:00:20.201107,2020-11-07 21:16:01.687002,2020-11-06 11:11:36.149002,2020-01-06 21:57:59.890,2020-01-06 21:57:59.890,2020-11-07 21:10:30.866,2020-11-07 21:10:30.866
10938,1970-01-01 00:00:20.201107,2020-11-07 15:54:36.799002,2020-11-07 03:34:50.330002,2020-03-15 04:53:59.606,2020-03-15 04:53:59.606,2020-11-07 15:54:32.262,2020-11-07 15:54:32.262

### Checking out dataframe for appropriate features and dtypes

In [35]:
# Checking for appropriate dtypes & null values 
df_merge1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10939 entries, 0 to 10938
Data columns (total 80 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   event_date                       10939 non-null  datetime64[ns]
 1   event_timestamp                  10939 non-null  datetime64[ns]
 2   event_name                       10939 non-null  object
 3   event_previous_timestamp         10858 non-null  datetime64[ns]
 4   event_bundle_sequence_id         10939 non-null  object
 5   event_server_timestamp_offset    10939 non-null  object
 6   user_pseudo_id                   10939 non-null  object
 7   user_first_touch_timestamp       10939 non-null  datetime64[ns]
 8   stream_id                        10939 non-null  object
 9   platform                         10939 non-null  object
 10  device.category                  10939 non-null  object
 11  device.mobile_brand_name         10697 non-null  object
 12  device.mobile_model_name         10697 non-null  object
 13  device.mobile_os_hardware_model  10939 non-null  object
 14  device.operating_system          10939 non-null  object
 15  device.operating_system_version  10939 non-null  object
 16  device.language                  10939 non-null  object
 17  device.is_limited_ad_tracking    10939 non-null  object
 18  device.time_zone_offset_seconds  10939 non-null  object
 19  geo.continent                    10939 non-null  object
 20  geo.country                      10939 non-null  object
 21  geo.region                       10939 non-null  object
 22  geo.city                         10939 non-null  object
 23  geo.sub_continent                10939 non-null  object
 24  geo.metro                        10939 non-null  object
 25  app_info.id                      10939 non-null  object
 26  app_info.version                 10939 non-null  object
 27  app_info.firebase_app_id         10939 non-null  object
 28  app_info.install_source          10939 non-null  object
 29  traffic_source.medium            10939 non-null  object
 30  traffic_source.source            10939 non-null  object
 31  ecommerce.unique_items           974 non-null    object
 32  device.mobile_marketing_name     677 non-null    object
 33  traffic_source.name              10261 non-null  object
 34  device.vendor_id                 9926 non-null   object
 35  ecommerce.transaction_id         7 non-null      object
 36  index1                           10939 non-null  object
 37  first_open_time.value            10939 non-null  int64
 38  first_open_time.timestamp        10939 non-null  datetime64[ns]
 39  ga_session_number.value          10921 non-null  float64
 40  ga_session_number.timestamp      10921 non-null  datetime64[ns]
 41  ga_session_id.value              10921 non-null  float64
 42  ga_session_id.timestamp          10921 non-null  datetime64[ns]
 43  firebase_event_origin_x          10939 non-null  object
 44  firebase_event_origin_y          10939 non-null  object
 45  ga_session_id                    10921 non-null  object
 46  engaged_session_event            10645 non-null  object
 47  session_engaged                  452 non-null    object
 48  ga_session_number                10921 non-null  object
 49  firebase_screen_id               10486 non-null  object
 50  firebase_screen_class            10486 non-null  object
 51  engagement_time_msec             4707 non-null   object
 52  entrances                        473 non-null    object
 53  freeride                         212 non-null    object
 54  firebase_previous_id             3629 non-null   object
 55  firebase_previous_class          3629 non-null   object
 56  item_subcategory                 904 non-null    object
 57  recommended                      974 non-null    object
 58  item_category                    951 non-null    object
 59  item_name                        974 non-null    object
 60  item_number                      974 non-null    object
 61  item_id                          974 non-null    object
 62  debug_event                      242 non-null    object
 63  previous_os_version              57 non-null     object
 64  campaign_info_source             3 non-null      object
 65  medium                           3 non-null      object
 66  source                           3 non-null      object
 67  system_app                       3 non-null      object
 68  system_app_update                3 non-null      object
 69  update_with_analytics            10 non-null     object
 70  firebase_conversion              10 non-null     object
 71  previous_first_open_count        10 non-null     object
 72  search_term                      802 non-null    object
 73  search_book                      802 non-null    object
 74  search_type                      802 non-null    object
 75  search_subcategory               59 non-null     object
 76  search_category                  59 non-null     object
 77  previous_app_version             2 non-null      object
 78  timestamp                        3 non-null      object
 79  timestamp_double                 8 non-null      float64
dtypes: datetime64[ns](7), float64(3), int64(1), object(69)
memory usage: 6.8+ MB

In [36]:
print_full(df_merge1.head(1).T)

                                                                      0
event_date                                   1970-01-01 00:00:20.201107
event_timestamp                              2020-11-08 02:15:18.108000
event_name                                                session_start
event_previous_timestamp                     2020-11-07 21:47:54.744000
event_bundle_sequence_id                                             13
event_server_timestamp_offset                                    754702
user_pseudo_id                         cb052c8ce7b261aecf783ce043089fb3
user_first_touch_timestamp                   2019-07-13 00:27:23.627000
stream_id                                                    1440534155
platform                                                        ANDROID
device.category                                                  mobile
device.mobile_brand_name                                         Google
device.mobile_model_name                                          Pixel
device.mobile_os_hardware_model                                   Pixel
device.operating_system                                         ANDROID
device.operating_system_version                                      10
device.language                                                   en-us
device.is_limited_ad_tracking                                        No
device.time_zone_offset_seconds                                  -21600
geo.continent                                                  Americas
geo.country                                               United States
geo.region                                                        Texas
geo.city                                                         Austin
geo.sub_continent                                      Northern America
geo.metro                                                     (not set)
app_info.id                                     org.livingletter.hymnal
app_info.version                                                  1.1.7
app_info.firebase_app_id         1:76837103840:android:e1d753a7fbfeeaac
app_info.install_source                             com.android.vending
traffic_source.medium                                           organic
traffic_source.source                                       google-play
ecommerce.unique_items                                              NaN
device.mobile_marketing_name                                        NaN
traffic_source.name                                                 NaN
device.vendor_id                                                    NaN
ecommerce.transaction_id                                            NaN
index1                                                                0
first_open_time.value                                     1562979600000
first_open_time.timestamp                    2019-07-13 00:27:23.627000
ga_session_number.value                                               8
ga_session_number.timestamp                  2020-11-08 02:15:18.108000
ga_session_id.value                                          1.6048e+09
ga_session_id.timestamp                      2020-11-08 02:15:18.108000
firebase_event_origin_x                                            auto
firebase_event_origin_y                                            auto
ga_session_id                                                1604801718
engaged_session_event                                                 1
session_engaged                                                       1
ga_session_number                                                     8
firebase_screen_id                                                  NaN
firebase_screen_class                                               NaN
engagement_time_msec                                                NaN
entrances                                                           NaN
freeride                                                            NaN
firebase_previous_id                                                NaN
firebase_previous_class                                             NaN
item_subcategory                                                    NaN
recommended                                                         NaN
item_category                                                       NaN
item_name                                                           NaN
item_number                                                         NaN
item_id                                                             NaN
debug_event                                                         NaN
previous_os_version                                                 NaN
campaign_info_source                                                NaN
medium                                                              NaN
source                                                              NaN
system_app                                                          NaN
system_app_update                                                   NaN
update_with_analytics                                               NaN
firebase_conversion                                                 NaN
previous_first_open_count                                           NaN
search_term                                                         NaN
search_book                                                         NaN
search_type                                                         NaN
search_subcategory                                                  NaN
search_category                                                     NaN
previous_app_version                                                NaN
timestamp                                                           NaN
timestamp_double                                                    NaN

### Removing unimportant columns with too many null values

In [37]:
# Removing columns that have too many null values OR consist of unimportant values
df_merge1 = df_merge1.drop(['ecommerce.unique_items', 'device.mobile_marketing_name', 'ecommerce.transaction_id', 'traffic_source.name', 'app_info.firebase_app_id', 'app_info.id', 'geo.metro', 'campaign_info_source', 'medium', 'source', 'system_app', 'system_app_update', 'update_with_analytics', 'firebase_conversion', 'previous_first_open_count', 'previous_app_version', 'timestamp','timestamp_double'], 1)

# Converting main df to csv

In [38]:
# save the data to a new csv file
datapath = '../Project Hymnal/data'
save_file(df_merge1, 'df.csv', datapath)

A file already exists with this name.

Do you want to overwrite? (Y/N)Y
Writing file.  "../Project Hymnal/data\df.csv"

# Getting overview of data using pandas Profiling

In [39]:
from pandas_profiling import ProfileReport

profile = ProfileReport(df_merge1, title = 'Pandas Profiling Report',explorative = True)

In [40]:
plt.style.use('classic')

In [ ]:
profile.to_notebook_iframe()